version: '3'
services:
  app:
    build:
      context: .
    container_name: pycascades
    image: pycascades/cms
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      CONFERENCE_YEAR: 2023
    command: poetry run python manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
