version: '3'
services:
  app:
    build:
      context: ./
    container_name: pycascades
    image: pycascades/cms
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
    command: /bin/bash
    tty: true
    stdin_open: true
