version: '3'
services:
  app:
    build:
      context: .
    container_name: pycascades
    image: pycascades/cms
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: poetry run python manage.py runserver
    tty: true
    stdin_open: true
