[tool.poetry]
name = "pycascades-cms"
version = "0.1.0"
description = ""
authors = ["Seb Vetter <seb@pycascades.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.0"
wagtail = "^2.11.3"
wagtail-bakery = "^0.5.0"
wagtailnetlify = "^0.7"
gunicorn = "^20.0.4"
django-heroku = "^0.3.1"
pyjade = "^4.0.0"
django-assets = "^2.0"
django-storages = "^1.11.1"
sentry-sdk = "^0.19.5"

[tool.poetry.dev-dependencies]
cssmin = "^0.2.0"
jsmin = "^2.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
