# Generated by Django 3.1.4 on 2021-01-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='section',
            field=models.CharField(choices=[('chair', 'chair'), ('organizer', 'organizer'), ('emeritus', 'emeritus')], default='organizer', max_length=50),
        ),
    ]
