# Generated by Django 4.1.3 on 2022-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_organizer_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="mastodon",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
