# Generated by Django 3.1.5 on 2021-01-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_pretalxschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pretalxschedule',
            name='pretalx_event_url',
            field=models.URLField(blank=True, verbose_name='Pretalx Event URL'),
        ),
    ]
