# Generated by Django 4.1.3 on 2022-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0003_auto_20210118_0112"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="mastodon",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
