# Generated by Django 3.1.5 on 2021-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netlify_id", models.CharField(max_length=30, null=True)),
                ("url", models.URLField(null=True)),
                ("deployment_url", models.URLField(null=True)),
                (
                    "datetime_started",
                    models.DateTimeField(
                        auto_now_add=True, help_text="deployment started"
                    ),
                ),
                (
                    "datetime_finished",
                    models.DateTimeField(
                        null=True, verbose_name="deployment completed"
                    ),
                ),
            ],
        ),
    ]
