# Generated by Django 3.1.5 on 2021-01-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0002_netlifyconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deploys",
                to="deployment.netlifyconfiguration",
            ),
        ),
    ]
