# Generated by Django 3.1.5 on 2021-01-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_netlifyconfiguration_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netlifyconfiguration',
            name='netlify_id',
            field=models.CharField(max_length=100),
        ),
    ]
