# Generated by Django 3.1.5 on 2021-01-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0006_auto_20210110_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="message",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
