# Generated by Django 3.1.5 on 2021-01-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0007_deployment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='builder',
            field=models.CharField(choices=[('build', 'Default Wagtail Build'), ('netlify_build', 'Custom PyCascades Build')], default='netlify_build', max_length=100),
        ),
    ]
