# Generated by Django 3.1.5 on 2021-01-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0008_deployment_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='logs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
