# Generated by Django 5.0.2 on 2024-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0004_auto_20210114_0411"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsortier",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Sorting order on the page (higher number means higher up)",
            ),
        ),
    ]
