# Generated by Django 3.1.5 on 2021-01-11 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("home", "0007_homepage_custom_template_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
