# Generated by Django 3.2.9 on 2021-11-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_homepage_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="background_attribution",
            field=models.TextField(
                blank=True, verbose_name="Background image attribution"
            ),
        ),
    ]
