# Generated by Django 4.1.3 on 2022-12-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_homepage_background_attribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastodonVerification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
    ]
