# Generated by Django 4.1.3 on 2022-12-28 21:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0078_referenceindex"),
        ("home", "0010_mastodonverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenuePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("venue_content", wagtail.fields.RichTextField(blank=True)),
                (
                    "venue_attribution",
                    models.TextField(
                        blank=True,
                        help_text="HTML allowed",
                        verbose_name="Venue image attribution",
                    ),
                ),
                ("location_address", wagtail.fields.RichTextField()),
                ("location_lat", models.DecimalField(decimal_places=17, max_digits=20)),
                (
                    "location_long",
                    models.DecimalField(decimal_places=17, max_digits=20),
                ),
                (
                    "location_google_maps_url",
                    models.CharField(blank=True, max_length=500),
                ),
                ("accommodation_content", wagtail.fields.RichTextField(blank=True)),
                (
                    "accommodation_attribution",
                    models.TextField(
                        blank=True,
                        help_text="HTML allowed",
                        verbose_name="Accommodation image attribution",
                    ),
                ),
                (
                    "accommodation_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "venue_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
