# Generated by Django 4.1.3 on 2024-02-08 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_venuepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venuepage",
            name="accommodation_attribution",
        ),
        migrations.RemoveField(
            model_name="venuepage",
            name="accommodation_content",
        ),
        migrations.RemoveField(
            model_name="venuepage",
            name="accommodation_photo",
        ),
    ]
