# Generated by Django 3.1.5 on 2021-01-17 03:35

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("location", wagtail.core.fields.RichTextField(blank=True)),
                ("description", wagtail.core.fields.RichTextField(blank=True)),
                ("post_url", models.CharField(blank=True, max_length=2000)),
                ("apply_url", models.CharField(blank=True, max_length=2000)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
