# Generated by Django 3.1.5 on 2021-01-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_auto_20210114_0411'),
        ('jobs', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsors.sponsor'),
        ),
    ]
