# Generated by Django 3.1.5 on 2021-01-17 03:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_auto_20210117_0351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="locations",
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
