# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_netlify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
        cache: poetry
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.2.1
    - name: Install dependencies
      run: |
        poetry install

    - name: Test Netlify Build Command
      run: |
        poetry run python manage.py migrate
        poetry run python manage.py netlify_build

  test_static_assets:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
          cache: poetry
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.1
      - name: Install dependencies
        run: |
          poetry install

      - name: Test Collecting Static Assets
        run: |
          poetry run python manage.py migrate
          poetry run python manage.py collectstatic --noinput
          poetry run python manage.py assets build

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - uses: pre-commit/action@v3.0.0
